application:
  version: #web.version#

debug: false
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false
    cache-enabled: false
server:
  port: 8501
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: true
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/his?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false"
      username: root
      password: 123456
      initial-size: 5
      max-active: 200
      max-wait: 10000
      min-idle: 5
      pool-prepared-statements: true
      validation-query: "SELECT 1 FROM DUAL"
      time-between-eviction-runs-millis: 60000
      remove-abandoned: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: mergeStat

  main:
    allow-bean-definition-overriding: true
  redis:
    host: 114.55.175.233
    port: 6379
    database: 1
    password: 98761234
  session:
    store-type: redis
    timeout: 86400
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
usercenter:
  LoginFilter:
    enable: true
